# H2 Database ??? ??????
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ????????? SQL ?????????????
spring.sql.init.mode=never

# ????????? Actuator ??? ??????
management.endpoints.enabled-by-default=false

# Logging
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
