# Server Configuration
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:shareit
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Disable SQL script initialization
spring.sql.init.mode=never

# Actuator Configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.ru.practicum.shareit=DEBUG
